# Generated by Django 4.0.4 on 2022-04-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgae', models.ImageField(default=' ', upload_to='static/Images')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=300)),
                ('rDate', models.DateField()),
                ('total_actors', models.IntegerField()),
                ('vote', models.IntegerField()),
            ],
        ),
    ]
