# Generated by Django 4.0.4 on 2022-04-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_actorlist_remove_movielist_id_movielist_id_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorlist',
            name='Id',
            field=models.AutoField(default=' ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='Id',
            field=models.AutoField(default=' ', primary_key=True, serialize=False),
        ),
    ]
