# Generated by Django 4.0.4 on 2022-04-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_alter_actorlist_id_alter_movielist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorlist',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
